accounts/urls.py
from django.urls import path, include
from accounts.views import profile, edit_profile, edit_avatar


urlpatterns = [
    path('profile/', profile, name='profile'),
    path('edit/', edit_profile, name='edit_profile'),
    path('edit/avatar/', edit_avatar, name='edit_avatar'),
    path('', include('allauth.urls')),
]

cart/urls.py
from django.urls import path
from cart.views import cart_detail, add_to_cart, remove_from_cart

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from store.views import home, product_detail, product_list

app_name = 'store'

urlpatterns = [
    path('', home, name='home'),
    path('products/', product_list, name='product_list'),
    path('products/<int:pk>/', product_detail, name='product_detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.
def profile(request):
    # Logic to display user profile
    return render(request, 'accounts/profile.html')

def edit_profile(request):
    # Logic to edit user profile
    return render(request, 'accounts/edit_profile.html')    

def edit_avatar(request):
    # Logic to edit user avatar
    return render(request, 'accounts/edit_avatar.html')

cart/views.py
from django.shortcuts import render

# Create your views here.
def cart_detail(request):
    # Logic to display cart details
    return render(request, 'cart/cart_detail.html')

def add_to_cart(request, product_id):
    # Logic to add a product to the cart
    return render(request, 'cart/cart_detail.html')
def remove_from_cart(request, product_id):
    # Logic to remove a product from the cart
    return render(request, 'cart/cart_detail.html')

store/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    # Logic to display the home page
    return render(request, 'store/home.html')

def product_list(request):
    # Logic to display a list of products
    return render(request, 'store/product_list.html')

def product_detail(request, pk):
    # Logic to display product details
    return render(request, 'store/product_detail.html')

templates/accounts/login.html
{% load static %}

{% include 'partials/forms.py' %}

templates/base.html
<!DOCTYPE html>
<html lang="vi">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if title %}
            {{ title }} | VPP Giáo Thòn
        {% else %}
            VPP Giáo Thòn - Cung cấp văn phòng phẩm chất lượng
        {% endif %}   
    </title>
    <link rel="icon" href="{% static 'images/logo/logo.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    
    {% block navbar %}
        {% include 'partials/navbar.html' %}
    {% endblock navbar %}
        
    <div class="my-3">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'partials/modals.html' %}
    
    
    
    <!-- scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/excercise.js' %}"></script>
</body>
</html>

templates/partials/carousel.html
{% load static %}
<div id="carouselHeroDark" class="carousel carousel-dark slide">
    <div class="overly">

    </div>
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselHeroDark" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselHeroDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselHeroDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselHeroDark" data-bs-slide-to="3" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner rounded-2 shadow-lg">
        <div class="carousel-item active" data-bs-interval="10000">
            <img src="{% static 'images/carousels/banner1.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="text-uppercase fs-1 fw-bold text-left">Tên Sản phẩm</h1>
                <p>Some representative placeholder content for the first slide.</p>
                <a href="#" class="btn btn-primary text-uppercase fw-bold rounded-5">Mua Ngay</a>
            </div>
        </div>
        <div class="carousel-item" data-bs-interval="2000">
            <img src="{% static 'images/carousels/banner2.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="text-uppercase fs-1 fw-bold text-left">Tên Sản phẩm</h1>
                <p>Some representative placeholder content for the first slide.</p>
                <a href="#" class="btn btn-primary text-uppercase fw-bold rounded-5">Mua Ngay</a>
            </div>
        </div>
        <div class="carousel-item" data-bs-interval="3000">
            <img src="{% static 'images/carousels/banner3.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="text-uppercase fs-1 fw-bold text-left">Tên Sản phẩm</h1>
                <p>Some representative placeholder content for the first slide.</p>
                <a href="#" class="btn btn-primary text-uppercase fw-bold rounded-5">Mua Ngay</a>
            </div>
        </div>
        <div class="carousel-item" data-bs-interval="4000">
            <img src="{% static 'images/carousels/banner2.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1 class="text-uppercase fs-1 fw-bold text-left">Tên Sản phẩm</h1>
                <p>Some representative placeholder content for the first slide.</p>
                <a href="#" class="btn btn-primary text-uppercase fw-bold rounded-5">Mua Ngay</a>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselHeroDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselHeroDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

templates/partials/forms.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
    {% if title %}
        {{ title }}
    {% else %}
        Xác nhận
    {% endif %}
        </button>
</form>

templates/partials/modals.html
{% load static %}
<!-- Modal search -->
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">

                <form class="d-flex position-relative form-control rounded-pill" role="search">
                    <input class="ms-4 w-100 border border-0 search" type="search" placeholder="Tìm kiếm sản phẩm . . . . "
                    aria-label="Search" />
                    <button class="border-0 bg-transparent rounded-pill position-absolute top-0 start-0 ms-2 mt-1"
                    type="submit"><i class="bi bi-search fw-bold fs-5 search-icon"></i></button>
                </form>   
                <div class="mt-3">
                    Tim kiem hien thi o day
                </div>
            </div>

        </div>
    </div>
</div>

<!-- Modal search -->
<div class="modal fade" id="cartModal" tabindex="-1" aria-labelledby="cartModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            
            <div class="modal-header bg-info-subtle text-primary">
                <h1 class="modal-title fs-5" id="cartModalLabel">
                    {% if cart and request.user.is_authenticated %} 
                        Giỏ hàng của {{ user.username }}
                    {% else %}
                        Giỏ hàng của bạn đang trống
                    {% endif %}
                </h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% if cart %}
                    Giỏ hàng hiển thị ở đây
                {% else %}
                    <div class="modal-body text-center">
                        <p class="mb-4">Hãy thêm sản phẩm vào giỏ hàng để tiến hành thanh toán</p>
                        <i class="bi bi-cart4 text-info" style="font-size: 14rem;"></i>
                    </div>
                {% endif %}
            </div>
            <div class="modal-footer">
                {% if cart %}
                    <a href="{% url 'cart' %}" class="btn btn-primary">Xem giỏ hàng</a>
                    <a href="{% url 'checkout' %}" class="btn btn-success">Thanh toán</a>
                {% else %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/partials/navbar.html
{% load static %}
<div class="navbar-header">
  <div class="row container-fluid py-4">
    <div
      class="col-lg-2 d-none d-sm-block d-sm-none d-md-block d-md-none d-lg-block"
    >
      <div class="d-flex justify-content-start align-items-center">
        <a class="me-3 text-info" href="#"
          ><i class="bi bi-facebook fs-4"></i
        ></a>
        <a class="me-3 text-primary" href="#"
          ><i class="bi bi-instagram fs-4"></i
        ></a>
        <a class="me-3 text-primary" href="#"
          ><i class="bi bi-twitter fs-4"></i
        ></a>
        <a class="me-3 text-danger" href="#"
          ><i class="bi bi-youtube fs-4"></i
        ></a>
      </div>
    </div>
    <div
      class="col-lg-3 d-none d-sm-block d-sm-none d-md-block d-md-none d-lg-block"
    >
      <div class="d-flex justify-content-center align-items-center">
        <i class="bi bi-telephone-fill text-primary fs-5 me-2"></i>
        <span class="fw-bold text-primary fs-6 fw-lighter"
          >Hotline: 1900 6750</span
        >
      </div>
    </div>

    <div class="col-lg-7 justify-content-center align-items-center d-flex">
      <a class="me-3 text-primary nav-link" href="#"
        ><i class="bi bi-geo-alt-fill fs-6 fw-lighter"></i> Hệ thống cửa hàng</a
      >
      <a class="me-3 text-primary nav-link" href="#"
        ><i class="bi bi-question-circle-fill fs-6"></i> Hỗ trợ</a
      >
      <a class="me-3 text-primary nav-link" href="#"
        ><i class="bi bi-shield-lock-fill fs-6"></i> Đăng nhập</a
      >
      <a class="text-primary nav-link" href="#"
        ><i class="bi bi-person-plus-fill fs-6"></i> Đăng ký</a
      >
    </div>
  </div>
</div>
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-lg-top">
  <div class="container-fluid">
    <a class="navbar-brand text-primary" href="{% url 'store:home' %}">
      <img
        src="{% static 'images/logo/logo.ico' %}"
        alt="logo"
        width="30"
        height="30"
      />
      <span class="d-lg-none">VPP Giáo Thòn</span>
    </a>
    <form
      class="d-flex d-lg-none position-relative"
      role="search"
      data-bs-toggle="modal"
      data-bs-target="#searchModal"
    >
      <input
        class="me-4 form-control rounded-pill search"
        type="text"
        placeholder="Tìm kiếm sản phẩm . . . . "
        aria-label="Search"
      />
      <button
        class="border-0 bg-transparent rounded-pill position-absolute top-0 end-0 me-4 mt-1"
        type="button"
        data-bs-toggle="modal"
        data-bs-target="#searchModal"
      >
        <i class="bi bi-search fw-bold fs-5 search-icon"></i>
      </button>
    </form>
    <div class="d-flex position-relative d-lg-none">
      <div class="nav-item">
        <a
          class="nav-link"
          href="#"
          data-bs-toggle="modal"
          data-bs-target="#cartModal"
        >
          <button
            type="button"
            class="btn btn-outline-primary position-relative rounded-pill"
          >
            <i class="bi bi-cart3 fs-5"></i>
            <span
              class="position-absolute top-0 start-100 translate-middle badge rounded-circle p-2 bg-danger border border-light"
            >
              9+
              <span class="visually-hidden">unread messages</span>
            </span>
          </button>
        </a>
      </div>

      <p
        class="d-lg-none ms-3 mt-2"
        type="button"
        data-bs-toggle="offcanvas"
        data-bs-target="#offcanvasRight"
        aria-controls="offcanvasRight"
      >
        <span class="navbar-toggler-icon"></span>
      </p>
    </div>

    <div
      class="collapse navbar-collapse grid justify-content-between"
      id="navbarSupportedContent"
    >
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item navbar-vertical dropdown">
          <a
            class="nav-link active dropdown-toggle bg-primary text-white"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Danh mục sản phẩm
          </a>
          <ul class="dropdown-menu">
            <!-- Sub menu cấp 2 -->
            <li class="dropdown-submenu">
              <a href="#" class="dropdown-item dropdown-toggle"
                >Văn phòng phẩm</a
              >
              <ul class="dropdown-menu">
                <li>
                  <a href="#" class="dropdown-item">Bút dsafdadfsaf fasfdsa</a>
                </li>
                <li><a href="#" class="dropdown-item">Giấy</a></li>
                <li><a href="#" class="dropdown-item">Sổ</a></li>
                <li><a href="#" class="dropdown-item">Kẹp</a></li>
                <li><a href="#" class="dropdown-item">Hồ sơ</a></li>
              </ul>
            </li>
            <li><a href="#" class="dropdown-item">Thiết bị văn phòng</a></li>
            <li><a href="#" class="dropdown-item">Đồ dùng học tập</a></li>
          </ul>
        </li>
        <li class="nav-item navbar-vertical">
          <a class="nav-link" href="#">Liên hệ</a>
        </li>
        <li class="nav-item navbar-vertical">
          <a class="nav-link" href="#">Hướng dẫn thanh toán</a>
        </li>
        <li class="nav-item navbar-vertical">
          <a class="nav-link" href="#">Đánh giá/Góp ý</a>
        </li>
        <li class="nav-item navbar-vertical">
          <a class="nav-link" href="#">Tin tức</a>
        </li>
      </ul>
      <!-- Show in >= 768px -->
      <form
        class="d-flex position-relative d-none d-sm-block d-sm-none d-md-block d-md-none d-lg-block"
        role="search"
        data-bs-toggle="modal"
        data-bs-target="#searchModal"
      >
        <input
          class="me-4 form-control rounded-pill search"
          type="text"
          placeholder="Tìm kiếm sản phẩm . . . . "
          aria-label="Search"
        />
        <button
          class="border-0 bg-transparent rounded-pill position-absolute top-0 end-0 me-2 mt-1"
          type="button"
          data-bs-toggle="modal"
          data-bs-target="#searchModal"
        >
          <i class="bi bi-search fw-bold fs-5 search-icon"></i>
        </button>
      </form>
      <ul
        class="navbar-nav mb-2 mb-lg-0 d-flex flex-row justify-content-center align-items-center"
      >
        <li
          class="nav-item d-flex position-relative d-none d-sm-flex d-sm-none d-md-flex d-md-none d-lg-flex"
        >
          <a
            class="nav-link"
            href="#"
            data-bs-toggle="modal"
            data-bs-target="#cartModal"
          >
            <button
              type="button"
              class="btn btn-outline-primary position-relative rounded-pill"
            >
              <i class="bi bi-cart3 fs-5"></i>
              <span
                class="position-absolute top-0 start-100 translate-middle badge rounded-circle p-1 bg-danger border border-light"
              >
                9+
                <span class="visually-hidden">unread messages</span>
              </span>
            </button>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div
  class="offcanvas offcanvas-end"
  tabindex="-1"
  id="offcanvasRight"
  aria-labelledby="offcanvasRightLabel"
>
  <div class="offcanvas-header">
    <form
      class="d-flex position-relative d-lg-none ms-auto"
      role="search"
      data-bs-toggle="modal"
      data-bs-target="#searchModal"
    >
      <input
        class="form-control rounded-pill search"
        type="text"
        placeholder="Tìm kiếm sản phẩm . . . . "
        aria-label="Search"
      />
      <button
        class="border-0 bg-transparent rounded-pill position-absolute top-0 end-0 me-2 mt-1"
        type="button"
        data-bs-toggle="modal"
        data-bs-target="#searchModal"
      >
        <i class="bi bi-search fw-bold fs-5 search-icon"></i>
      </button>
    </form>

    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="offcanvas"
      aria-label="Close"
    ></button>
  </div>
  <div class="offcanvas-body">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Liên hệ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Hướng dẫn thanh toán</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Đánh giá/Góp ý</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Tin tức</a>
      </li>
    </ul>
  </div>
</div>

templates/partials/offcanvas.html
{% load static %}
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <form class="d-flex position-relative d-lg-none ms-auto" role="search" data-bs-toggle="modal"
            data-bs-target="#searchModal">
            <input class="form-control rounded-pill search" type="text" placeholder="Tìm kiếm sản phẩm . . . . "
                aria-label="Search" />
            <button class="border-0 bg-transparent rounded-pill position-absolute top-0 end-0 me-2 mt-1" type="button"
                data-bs-toggle="modal" data-bs-target="#searchModal"><i
                    class="bi bi-search fw-bold fs-5 search-icon"></i></button>
        </form>

        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Liên hệ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Hướng dẫn thanh toán</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Đánh giá/Góp ý</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Tin tức</a>
            </li>
        </ul>
    </div>
</div>